SRCDIR = ..

# Test programs to compile, and a list of sources for each.
# To add a new test, put its name on the PROGS list
# and then add a name_SRC line that lists its source files.
PROGS = cat cmp cp echo halt hex-dump ls mcat mcp mkdir pwd rm shell \
	bubsort insult lineup matmult recursor \
	sumargv lab2test lab1test lab1test2 pfs pfs_reader pfs_writer dummy longrun \
	child parent create-bad create-normal

# Added test programs
sumargv_SRC = sumargv.c
lab2test_SRC = lab2test.c
lab1test_SRC = lab1test.c
lab1test2_SRC = lab1test2.c
pfs_SRC = pfs.c
pfs_reader_SRC = pfs_reader.c
pfs_writer_SRC = pfs_writer.c
longrun_SRC = longrun.c
dummy_SRC = dummy.c
child_SRC = child.c
parent_SRC = parent.c
create-bad_SRC = create-bad.c
create-normal_SRC = create-normal.c

# Should work from project 2 onward.
cat_SRC = cat.c
cmp_SRC = cmp.c
cp_SRC = cp.c
echo_SRC = echo.c
halt_SRC = halt.c
hex-dump_SRC = hex-dump.c
insult_SRC = insult.c
lineup_SRC = lineup.c
ls_SRC = ls.c
recursor_SRC = recursor.c
rm_SRC = rm.c

# Should work in project 3; also in project 4 if VM is included.
bubsort_SRC = bubsort.c
matmult_SRC = matmult.c
mcat_SRC = mcat.c
mcp_SRC = mcp.c

# Should work in project 4.
mkdir_SRC = mkdir.c
pwd_SRC = pwd.c
shell_SRC = shell.c

include $(SRCDIR)/Make.config
include $(SRCDIR)/Makefile.userprog
